# Database connection settings
hibernate.connection.url=jdbc:postgresql://dpg-d00f1bs9c44c73fk11l0-a.frankfurt-postgres.render.com/turntheslayerxd_second_postgresql
hibernate.connection.username=turntheslayerxd_second_postgresql_user
hibernate.connection.password=4H61MWNEDek2Xpqi5F0MmTDD5URSulza

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

# Automatically export the schema
hibernate.hbm2ddl.auto=update

hibernate.default_schema=cat_service

# dialect and driver 
hibernate.connection.driver_class=org.postgresql.Driver
