/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {         
        url = uri("https://mvnrepository.com")
    }
}

dependencies {
    testImplementation(libs.junit)

    implementation(libs.guava)

    
    implementation("org.postgresql:postgresql:42.7.5")
    implementation("org.hibernate.orm:hibernate-community-dialects:7.0.0.CR1")
    implementation("org.hibernate.orm:hibernate-core:6.6.13.Final")
    implementation("jakarta.transaction:jakarta.transaction-api:2.0.1")   


    implementation(project(":services.module"))
    implementation(project(":data-access.module"))
    
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
