spring.datasource.url=jdbc:postgresql://dpg-d00f1bs9c44c73fk11l0-a.frankfurt-postgres.render.com:5432/turntheslayerxd_second_postgresql
spring.datasource.username=turntheslayerxd_second_postgresql_user
spring.datasource.password=4H61MWNEDek2Xpqi5F0MmTDD5URSulza
spring.jpa.show-sql=true
spring.datasource.hikari.schema=cat_service
spring.jpa.hibernate.ddl-auto=update